services:
  backend:
    image: node:20-alpine
    working_dir: /app
    container_name: solarcharge-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - '5001:5001'
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - solarcharge-network
    command: sh -c "npm install && npm run dev"

  frontend:
    image: node:20-alpine
    working_dir: /app
    container_name: solarcharge-frontend
    restart: unless-stopped
    env_file:
      - ./client/.env
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - solarcharge-network
    command: sh -c "npm install && npm run dev -- --host"

networks:
  solarcharge-network:
    driver: bridge